PLATFORM SETUP:--

-- Database
CREATE OR REPLACE DATABASE RETAIL_SALES_DB;

-- Schemas
CREATE OR REPLACE SCHEMA RETAIL_SALES_DB.RAW;
CREATE OR REPLACE SCHEMA RETAIL_SALES_DB.CURATED;

-- Warehouse
CREATE OR REPLACE WAREHOUSE RETAIL_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;



OBJECTS:--

USE DATABASE RETAIL_SALES_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT SALES_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE SALES_STAGE
FILE_FORMAT = SALES_CSV_FORMAT;

CREATE OR REPLACE TABLE SALES_RAW
(
    SALE_ID NUMBER,
    SALE_DATE DATE,
    STORE_ID VARCHAR(10),
    CUSTOMER_ID VARCHAR(20),
    PRODUCT_ID VARCHAR(20),
    QUANTITY NUMBER,
    AMOUNT NUMBER(10,2),
    STATUS VARCHAR(20),
    LAST_UPDATED_TS TIMESTAMP
);


USE SCHEMA CURATED;

CREATE OR REPLACE TABLE SALES_CURATED
(
    SALE_ID NUMBER,
    SALE_DATE DATE,
    STORE_ID VARCHAR(10),
    CUSTOMER_ID VARCHAR(20),
    PRODUCT_ID VARCHAR(20),
    QUANTITY NUMBER,
    AMOUNT NUMBER(10,2),
    STATUS VARCHAR(20),
    LAST_UPDATED_TS TIMESTAMP
);


USE SCHEMA RAW;

CREATE OR REPLACE STREAM SALES_STREAM
ON TABLE SALES_RAW;


CREATE OR REPLACE TASK RAW.SALES_TASK
WAREHOUSE = RETAIL_WH
SCHEDULE = '1 MINUTE'
AS
MERGE INTO CURATED.SALES_CURATED C
USING
(
    SELECT *
    FROM RAW.SALES_STREAM
) S
ON C.SALE_ID = S.SALE_ID

WHEN MATCHED
     AND S.STATUS = 'CANCELLED'
THEN DELETE

WHEN MATCHED
THEN UPDATE SET
    C.SALE_DATE       = S.SALE_DATE,
    C.STORE_ID        = S.STORE_ID,
    C.CUSTOMER_ID     = S.CUSTOMER_ID,
    C.PRODUCT_ID      = S.PRODUCT_ID,
    C.QUANTITY        = S.QUANTITY,
    C.AMOUNT          = S.AMOUNT,
    C.STATUS          = S.STATUS,
    C.LAST_UPDATED_TS = S.LAST_UPDATED_TS

WHEN NOT MATCHED
THEN INSERT
(
    SALE_ID,
    SALE_DATE,
    STORE_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    QUANTITY,
    AMOUNT,
    STATUS,
    LAST_UPDATED_TS
)
VALUES
(
    S.SALE_ID,
    S.SALE_DATE,
    S.STORE_ID,
    S.CUSTOMER_ID,
    S.PRODUCT_ID,
    S.QUANTITY,
    S.AMOUNT,
    S.STATUS,
    S.LAST_UPDATED_TS
);


(after data loaded)
ALTER TASK SALES_TASK RESUME;



