=============================
SALES_RAW VALIDATION QUERIES:

SELECT * FROM RAW.SALES_RAW ORDER BY SALE_ID;

--Total rows count
SELECT COUNT(*) AS RECORD_COUNT FROM RAW.SALES_RAW;

--Status Distribution
SELECT STATUS, COUNT(*) FROM RAW.SALES_RAW GROUP BY STATUS;

--Store-wise Distribution
SELECT STORE_ID, COUNT(*) FROM RAW.SALES_RAW GROUP BY STORE_ID ORDER BY STORE_ID;

--Duplicates check
SELECT SALE_ID, COUNT(*) FROM RAW.SALES_RAW GROUP BY SALE_ID HAVING COUNT(*) > 1;

--Null key-check validation
SELECT * FROM RAW.SALES_RAW WHERE SALE_ID IS NULL;

--Amount Summary
SELECT SUM(AMOUNT) AS TOTAL_AMOUNT FROM RAW.SALES_RAW;


=============================
SALES_STREAM VALIDATION QUERIES:

SELECT * FROM RAW.SALES_STREAM;

SELECT COUNT(*) AS RECORD_COUNT FROM RAW.SALES_STREAM;

--Action-wise Distribution
SELECT METADATA$ACTION, COUNT(*) FROM RAW.SALES_STREAM GROUP BY METADATA$ACTION;

--Update Identification
SELECT METADATA$ISUPDATE, COUNT(*) FROM RAW.SALES_STREAM GROUP BY METADATA$ISUPDATE;

--Full Stream View (important during update/delete testing)
SELECT SALE_ID, STATUS, METADATA$ACTION, METADATA$ISUPDATE FROM RAW.SALES_STREAM ORDER BY SALE_ID;


=============================
SALES_CURATED VALIDATION QUERIES:

SELECT * FROM CURATED.SALES_CURATED ORDER BY SALE_ID;

SELECT COUNT(*) AS RECORD_COUNT FROM CURATED.SALES_CURATED;

--Duplicate Check
SELECT SALE_ID, COUNT(*) FROM CURATED.SALES_CURATED GROUP BY SALE_ID HAVING COUNT(*) > 1;

--Status Distribution
SELECT STATUS, COUNT(*) FROM CURATED.SALES_CURATED GROUP BY STATUS;

--Store-wise Distribution
SELECT STORE_ID, COUNT(*) FROM CURATED.SALES_CURATED GROUP BY STORE_ID ORDER BY STORE_ID;

--Amount Summary
SELECT SUM(AMOUNT) AS TOTAL_AMOUNT FROM CURATED.SALES_CURATED;

--Compare Raw & Curated after Task processing
SELECT
    (SELECT COUNT(*) FROM RAW.SALES_RAW)      AS RAW_COUNT,
    (SELECT COUNT(*) FROM CURATED.SALES_CURATED) AS CURATED_COUNT;


=============================
LOADING SQL FROM STAGE TO TABLE:
COPY INTO RAW.SALES_RAW
FROM @RAW.SALES_STAGE/day1_sales.csv
FILE_FORMAT = (FORMAT_NAME = SALES_CSV_FORMAT);

COPY INTO RAW.SALES_RAW
FROM @RAW.SALES_STAGE/day2_sales.csv
FILE_FORMAT = (FORMAT_NAME = SALES_CSV_FORMAT);


=============================
VALIDATION QUERIES FOR REPORTING STAGE FROM CURATED LEVEL:

Store-wise Sales -- 
SELECT STORE_ID, COUNT(*) AS SALES_COUNT, SUM(AMOUNT) AS TOTAL_SALES FROM CURATED.SALES_CURATED GROUP BY STORE_ID ORDER BY STORE_ID;

Product-wise Sales --
SELECT PRODUCT_ID, COUNT(*) AS SALES_COUNT,SUM(AMOUNT) AS TOTAL_SALES FROM CURATED.SALES_CURATED GROUP BY PRODUCT_ID ORDER BY PRODUCT_ID;

Daily Sales Summary --
SELECT SAL*_DATE, COUNT(*) AS SALES_COUNT, SUM(QUANTITY) AS TOTAL_QUANTITY, SUM(AMOUNT) AS TOTAL_SALES FROM CURATED.SALES_CURATED GROUP BY SALE_DATE ORDER BY SALE_DATE;


=============================




